export default {

  // ==================== REAL ESTATE (5) ====================

  // 1. realestate-agency — "City Skyline Parallax" (Canvas 2D)
  'realestate-agency': '(function(){var isP=self!==top,C=document.getElementById("bg-canvas");if(isP){C.style.background="linear-gradient(180deg,#0a1628 0%,#1a2d4e 100%)";return;}var ctx=C.getContext("2d"),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener("resize",resize);document.addEventListener("mousemove",function(e){mx=e.clientX;my=e.clientY;});var buildings=[];for(var i=0;i<15;i++){buildings.push({x:Math.random()*2000-500,w:30+Math.random()*50,h:50+Math.random()*150,layer:Math.random()*3|0});}var raf;function draw(){ctx.clearRect(0,0,W,H);for(var i=0;i<buildings.length;i++){var b=buildings[i];var speed=(b.layer+1)*0.02;var px=b.x+(mx-W/2)*speed;var bx=((px%W)+W)%W-100;ctx.fillStyle="rgba(37,99,235,0.06)";ctx.fillRect(bx,H-b.h,b.w,b.h);for(var wy=10;wy<b.h-10;wy+=20){for(var wx=5;wx<b.w-5;wx+=15){ctx.fillStyle="rgba(37,99,235,0.03)";ctx.fillRect(bx+wx,H-b.h+wy,8,12);}}}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener("visibilitychange",function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();',

  // 2. realestate-luxury — "Gold Sparkle" (Canvas 2D)
  'realestate-luxury': '(function(){var isP=self!==top,C=document.getElementById("bg-canvas");if(isP){C.style.background="linear-gradient(135deg,#0a0a0a 0%,#1a1510 100%)";return;}var ctx=C.getContext("2d"),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener("resize",resize);document.addEventListener("mousemove",function(e){mx=e.clientX;my=e.clientY;});var sparks=[];for(var i=0;i<20;i++){sparks.push({x:Math.random()*2000,y:Math.random()*2000,s:1+Math.random()*2,phase:Math.random()*Math.PI*2,speed:0.01+Math.random()*0.02,vy:-0.1-Math.random()*0.2,vx:(Math.random()-0.5)*0.3});}var t=0;var raf;function draw(){ctx.clearRect(0,0,W,H);t+=0.016;for(var i=0;i<sparks.length;i++){var p=sparks[i];p.x+=p.vx;p.y+=p.vy;if(p.y<-10){p.y=H+10;p.x=Math.random()*W;}if(p.x<-10)p.x=W+10;if(p.x>W+10)p.x=-10;var osc=0.5+0.5*Math.sin(t*p.speed*60+p.phase);var alpha=0.15*osc;ctx.beginPath();ctx.arc(p.x%W,p.y%H,p.s,0,Math.PI*2);ctx.fillStyle="rgba(212,165,116,"+alpha+")";ctx.fill();}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener("visibilitychange",function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();',

  // 3. realestate-rental — "Map Pin Bounce" (Canvas 2D)
  'realestate-rental': '(function(){var isP=self!==top,C=document.getElementById("bg-canvas");if(isP){C.style.background="linear-gradient(180deg,#fafafa 0%,#f0f0f5 100%)";return;}var ctx=C.getContext("2d"),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener("resize",resize);document.addEventListener("mousemove",function(e){mx=e.clientX;my=e.clientY;});var pins=[];for(var i=0;i<8;i++){pins.push({x:100+Math.random()*(1600),y:100+Math.random()*(800),r:6+Math.random()*4,phase:Math.random()*Math.PI*2,amp:4+Math.random()*6,speed:0.8+Math.random()*0.6});}var t=0;var raf;function draw(){ctx.clearRect(0,0,W,H);t+=0.016;for(var i=0;i<pins.length;i++){var p=pins[i];var px=p.x%W;var py=(p.y%H)+Math.sin(t*p.speed+p.phase)*p.amp;ctx.beginPath();ctx.arc(px,py,p.r,0,Math.PI*2);ctx.fillStyle="rgba(239,68,68,0.15)";ctx.fill();ctx.beginPath();ctx.moveTo(px,py+p.r);ctx.lineTo(px,py+p.r+8);ctx.strokeStyle="rgba(239,68,68,0.1)";ctx.lineWidth=2;ctx.stroke();}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener("visibilitychange",function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();',

  // 4. realestate-invest — "Rising Bars" (Canvas 2D)
  'realestate-invest': '(function(){var isP=self!==top,C=document.getElementById("bg-canvas");if(isP){C.style.background="linear-gradient(180deg,#0a1628 0%,#0f1d32 100%)";return;}var ctx=C.getContext("2d"),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener("resize",resize);document.addEventListener("mousemove",function(e){mx=e.clientX;my=e.clientY;});var bars=[];var barCount=12;for(var i=0;i<barCount;i++){bars.push({maxH:60+Math.random()*180,delay:i*0.15});}function easeOutCubic(x){return 1-Math.pow(1-x,3);}var cycleTime=5;var t=0;var raf;function draw(){ctx.clearRect(0,0,W,H);t+=0.016;var ct=t%cycleTime;var barW=Math.min(40,W/(barCount*1.5));var totalW=barCount*(barW+10);var startX=(W-totalW)/2;for(var i=0;i<bars.length;i++){var b=bars[i];var elapsed=ct-b.delay;if(elapsed<0)elapsed=0;var progress=Math.min(elapsed/1.5,1);var eased=easeOutCubic(progress);var h=b.maxH*eased;ctx.fillStyle="rgba(16,185,129,0.06)";ctx.fillRect(startX+i*(barW+10),H-h-50,barW,h);}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener("visibilitychange",function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();',

  // 5. realestate-newdev — "Blueprint Lines" (Canvas 2D)
  'realestate-newdev': '(function(){var isP=self!==top,C=document.getElementById("bg-canvas");if(isP){C.style.background="linear-gradient(180deg,#fafafa 0%,#f5f7ff 100%)";return;}var ctx=C.getContext("2d"),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener("resize",resize);document.addEventListener("mousemove",function(e){mx=e.clientX;my=e.clientY;});var spacing=50;var raf;function draw(){ctx.clearRect(0,0,W,H);ctx.strokeStyle="rgba(37,99,235,0.04)";ctx.lineWidth=1;for(var x=0;x<W;x+=spacing){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke();}for(var y=0;y<H;y+=spacing){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke();}for(var x=0;x<W;x+=spacing){for(var y=0;y<H;y+=spacing){ctx.beginPath();ctx.arc(x,y,1.5,0,Math.PI*2);ctx.fillStyle="rgba(37,99,235,0.08)";ctx.fill();}}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener("visibilitychange",function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();',

  // ==================== FITNESS (4) ====================

  // 6. fitness-gym — "Energy Burst" (Canvas 2D)
  'fitness-gym': '(function(){var isP=self!==top,C=document.getElementById("bg-canvas");if(isP){C.style.background="linear-gradient(135deg,#0a0a0a 0%,#1a0505 100%)";return;}var ctx=C.getContext("2d"),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener("resize",resize);document.addEventListener("mousemove",function(e){mx=e.clientX;my=e.clientY;});var lines=[];var burstInterval=3;function createBurst(){lines=[];for(var i=0;i<40;i++){var angle=Math.random()*Math.PI*2;var speed=2+Math.random()*4;lines.push({angle:angle,dist:0,speed:speed,maxDist:150+Math.random()*300,alpha:0.3+Math.random()*0.3});}}createBurst();var t=0;var lastBurst=0;var raf;function draw(){ctx.clearRect(0,0,W,H);t+=0.016;if(t-lastBurst>burstInterval){createBurst();lastBurst=t;}var cx=W/2;var cy=H/2;for(var i=0;i<lines.length;i++){var l=lines[i];l.dist+=l.speed;if(l.dist>l.maxDist)continue;var progress=l.dist/l.maxDist;var alpha=l.alpha*(1-progress);var x1=cx+Math.cos(l.angle)*l.dist*0.5;var y1=cy+Math.sin(l.angle)*l.dist*0.5;var x2=cx+Math.cos(l.angle)*l.dist;var y2=cy+Math.sin(l.angle)*l.dist;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.strokeStyle="rgba(239,68,68,"+alpha+")";ctx.lineWidth=1.5;ctx.stroke();}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener("visibilitychange",function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();',

  // 7. fitness-coach — "Transform Pulse" (Canvas 2D)
  'fitness-coach': '(function(){var isP=self!==top,C=document.getElementById("bg-canvas");if(isP){C.style.background="linear-gradient(135deg,#0a0a0a 0%,#1a0808 100%)";return;}var ctx=C.getContext("2d"),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener("resize",resize);document.addEventListener("mousemove",function(e){mx=e.clientX;my=e.clientY;});var rings=[];for(var i=0;i<4;i++){rings.push({radius:0,maxRadius:Math.min(W,H)*0.4,phase:i*0.8,speed:1.2});}var t=0;var raf;function draw(){ctx.clearRect(0,0,W,H);t+=0.016;var cx=W/2;var cy=H/2;for(var i=0;i<rings.length;i++){var r=rings[i];var elapsed=(t+r.phase)%(2.5);var progress=elapsed/2.5;var radius=progress*r.maxRadius;var alpha=0.15*(1-progress);ctx.beginPath();ctx.arc(cx,cy,radius,0,Math.PI*2);ctx.strokeStyle="rgba(239,68,68,"+alpha+")";ctx.lineWidth=2;ctx.stroke();}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener("visibilitychange",function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();',

  // 8. fitness-yoga — "Water Ripple" (Canvas 2D)
  'fitness-yoga': '(function(){var isP=self!==top,C=document.getElementById("bg-canvas");if(isP){C.style.background="linear-gradient(180deg,#faf8f5 0%,#f0ebe5 100%)";return;}var ctx=C.getContext("2d"),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener("resize",resize);document.addEventListener("mousemove",function(e){mx=e.clientX;my=e.clientY;});var ripples=[];for(var i=0;i<3;i++){ripples.push({radius:0,phase:i*3.5,maxRadius:Math.min(W,H)*0.45});}var t=0;var raf;function draw(){ctx.clearRect(0,0,W,H);t+=0.016;var cx=W/2;var cy=H/2;for(var i=0;i<ripples.length;i++){var r=ripples[i];var elapsed=(t+r.phase)%10;var progress=elapsed/10;var radius=progress*r.maxRadius;var alpha=0.05*(1-progress);if(alpha<0)alpha=0;ctx.beginPath();ctx.arc(cx,cy,radius,0,Math.PI*2);ctx.strokeStyle="rgba(139,92,246,"+alpha+")";ctx.lineWidth=1;ctx.stroke();}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener("visibilitychange",function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();',

  // 9. fitness-nutrition — "Molecule Float" (Canvas 2D)
  'fitness-nutrition': '(function(){var isP=self!==top,C=document.getElementById("bg-canvas");if(isP){C.style.background="linear-gradient(180deg,#f0f9f4 0%,#e0f5e8 100%)";return;}var ctx=C.getContext("2d"),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener("resize",resize);document.addEventListener("mousemove",function(e){mx=e.clientX;my=e.clientY;});var clusters=[];for(var c=0;c<5;c++){var cx=Math.random()*1600;var cy=Math.random()*1000;var nodes=[];var numNodes=3+Math.floor(Math.random()*2);for(var n=0;n<numNodes;n++){nodes.push({ox:Math.random()*40-20,oy:Math.random()*40-20,r:4+Math.random()*6});}clusters.push({x:cx,y:cy,vx:(Math.random()-0.5)*0.3,vy:(Math.random()-0.5)*0.3,nodes:nodes});}var raf;function draw(){ctx.clearRect(0,0,W,H);for(var c=0;c<clusters.length;c++){var cl=clusters[c];cl.x+=cl.vx;cl.y+=cl.vy;if(cl.x<-100)cl.x=W+100;if(cl.x>W+100)cl.x=-100;if(cl.y<-100)cl.y=H+100;if(cl.y>H+100)cl.y=-100;for(var i=0;i<cl.nodes.length;i++){var n=cl.nodes[i];var nx=cl.x+n.ox;var ny=cl.y+n.oy;ctx.beginPath();ctx.arc(nx,ny,n.r,0,Math.PI*2);ctx.fillStyle="rgba(22,163,74,0.15)";ctx.fill();for(var j=i+1;j<cl.nodes.length;j++){var m=cl.nodes[j];ctx.beginPath();ctx.moveTo(nx,ny);ctx.lineTo(cl.x+m.ox,cl.y+m.oy);ctx.strokeStyle="rgba(22,163,74,0.1)";ctx.lineWidth=1;ctx.stroke();}}}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener("visibilitychange",function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();',

  // ==================== EDUCATION (4) ====================

  // 10. edu-online-course — "Floating Shapes" (Three.js)
  'edu-online-course': '(function(){var isP=self!==top,C=document.getElementById("bg-canvas");if(isP){C.style.background="linear-gradient(135deg,#f8faff 0%,#e0e7ff 100%)";return;}var W=innerWidth,H=innerHeight,mx=W/2,my=H/2;var scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(75,W/H,0.1,1000),renderer=new THREE.WebGLRenderer({canvas:C,alpha:true});renderer.setSize(W,H);renderer.setPixelRatio(Math.min(devicePixelRatio,2));camera.position.z=5;scene.add(new THREE.AmbientLight(0x404040));var pl=new THREE.PointLight(0xffffff,1,100);pl.position.set(5,5,5);scene.add(pl);document.addEventListener("mousemove",function(e){mx=e.clientX;my=e.clientY;});var shapes=[];var geoms=[new THREE.DodecahedronGeometry(0.8),new THREE.IcosahedronGeometry(0.7),new THREE.OctahedronGeometry(0.9)];var colors=[0x3b82f6,0x8b5cf6,0x06b6d4];for(var i=0;i<3;i++){var mat=new THREE.MeshBasicMaterial({color:colors[i],wireframe:true,transparent:true,opacity:0.3});var mesh=new THREE.Mesh(geoms[i],mat);mesh.position.x=(i-1)*3;mesh.position.y=Math.sin(i)*0.5;shapes.push(mesh);scene.add(mesh);}var t=0;function update(){t+=0.005;for(var i=0;i<shapes.length;i++){shapes[i].rotation.x=t*(0.3+i*0.1);shapes[i].rotation.y=t*(0.2+i*0.15);shapes[i].position.y=Math.sin(t*2+i*2)*0.3;}camera.position.x+=(((mx/W)-0.5)*2-camera.position.x)*0.02;camera.position.y+=(((my/H)-0.5)*-1-camera.position.y)*0.02;camera.lookAt(scene.position);}addEventListener("resize",function(){W=innerWidth;H=innerHeight;renderer.setSize(W,H);camera.aspect=W/H;camera.updateProjectionMatrix();});var raf;function loop(){raf=requestAnimationFrame(loop);update();renderer.render(scene,camera);}loop();document.addEventListener("visibilitychange",function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();',

  // 11. edu-bootcamp — "Code Characters" (Canvas 2D)
  'edu-bootcamp': '(function(){var isP=self!==top,C=document.getElementById("bg-canvas");if(isP){C.style.background="linear-gradient(180deg,#0a0a0a 0%,#0a1a0a 100%)";return;}var ctx=C.getContext("2d"),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener("resize",resize);document.addEventListener("mousemove",function(e){mx=e.clientX;my=e.clientY;});var chars="{ } [ ] ( ) ; < > = + - / * & | ~ ^".split(" ");var columns=[];var colCount=30;for(var i=0;i<colCount;i++){columns.push({x:(i/colCount)*2000,y:Math.random()*-1000,char:chars[Math.floor(Math.random()*chars.length)],speed:0.3+Math.random()*0.4});}var raf;function draw(){ctx.clearRect(0,0,W,H);ctx.font="14px monospace";for(var i=0;i<columns.length;i++){var c=columns[i];var px=c.x%(W+100);c.y+=c.speed;if(c.y>H+20){c.y=-20;c.char=chars[Math.floor(Math.random()*chars.length)];}ctx.fillStyle="rgba(34,197,94,0.08)";ctx.fillText(c.char,px,c.y);}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener("visibilitychange",function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();',

  // 12. edu-kids — "Rainbow Confetti" (Canvas 2D)
  'edu-kids': '(function(){var isP=self!==top,C=document.getElementById("bg-canvas");if(isP){C.style.background="linear-gradient(180deg,#fffbeb 0%,#fef3c7 100%)";return;}var ctx=C.getContext("2d"),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener("resize",resize);document.addEventListener("mousemove",function(e){mx=e.clientX;my=e.clientY;});var confetti=[];for(var i=0;i<35;i++){confetti.push({x:Math.random()*2000,y:Math.random()*1200,vy:0.2+Math.random()*0.5,vx:(Math.random()-0.5)*0.8,s:3+Math.random()*4,hue:Math.random()*360,rot:Math.random()*Math.PI*2,rotSpeed:(Math.random()-0.5)*0.03});}var raf;function draw(){ctx.clearRect(0,0,W,H);for(var i=0;i<confetti.length;i++){var p=confetti[i];p.y+=p.vy;p.vy+=0.01;p.x+=p.vx;p.rot+=p.rotSpeed;if(p.y>H+20){p.y=-20;p.vy=0.2+Math.random()*0.5;p.x=Math.random()*W;}var px=((p.x%W)+W)%W;ctx.save();ctx.translate(px,p.y);ctx.rotate(p.rot);ctx.fillStyle="hsla("+p.hue+",80%,60%,0.25)";ctx.fillRect(-p.s/2,-p.s/2,p.s,p.s);ctx.restore();}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener("visibilitychange",function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();',

  // 13. edu-tutor — "Chalk Dust" (Canvas 2D)
  'edu-tutor': '(function(){var isP=self!==top,C=document.getElementById("bg-canvas");if(isP){C.style.background="linear-gradient(180deg,#f8faff 0%,#f0f2f8 100%)";return;}var ctx=C.getContext("2d"),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener("resize",resize);document.addEventListener("mousemove",function(e){mx=e.clientX;my=e.clientY;});var dust=[];for(var i=0;i<60;i++){dust.push({x:Math.random()*2000,y:Math.random()*1200,s:1+Math.random()*2,vx:(Math.random()-0.5)*0.2,vy:(Math.random()-0.5)*0.2,life:Math.random()*Math.PI*2});}var t=0;var raf;function draw(){ctx.clearRect(0,0,W,H);t+=0.016;for(var i=0;i<dust.length;i++){var p=dust[i];p.x+=p.vx+Math.sin(t+p.life)*0.1;p.y+=p.vy+Math.cos(t*0.7+p.life)*0.1;if(p.x<-10)p.x=W+10;if(p.x>W+10)p.x=-10;if(p.y<-10)p.y=H+10;if(p.y>H+10)p.y=-10;ctx.beginPath();ctx.arc(p.x%W,p.y%H,p.s,0,Math.PI*2);ctx.fillStyle="rgba(100,100,120,0.04)";ctx.fill();}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener("visibilitychange",function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();',

  // ==================== EVENT (4) ====================

  // 14. event-conference — "Spotlight Sweep" (Canvas 2D)
  'event-conference': '(function(){var isP=self!==top,C=document.getElementById("bg-canvas");if(isP){C.style.background="linear-gradient(135deg,#0a0a0f 0%,#111118 100%)";return;}var ctx=C.getContext("2d"),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener("resize",resize);document.addEventListener("mousemove",function(e){mx=e.clientX;my=e.clientY;});var spots=[{color:"rgba(124,58,237,0.06)",size:280,speed:0.3,offset:0},{color:"rgba(6,182,212,0.04)",size:240,speed:0.25,offset:2},{color:"rgba(245,158,11,0.04)",size:300,speed:0.2,offset:4}];var t=0;var raf;function draw(){ctx.clearRect(0,0,W,H);t+=0.016;for(var i=0;i<spots.length;i++){var s=spots[i];var cx=W/2+Math.cos(t*s.speed+s.offset)*W*0.3;var cy=H/2+Math.sin(t*s.speed*0.7+s.offset)*H*0.25;var grad=ctx.createRadialGradient(cx,cy,0,cx,cy,s.size);grad.addColorStop(0,s.color);grad.addColorStop(1,"rgba(0,0,0,0)");ctx.fillStyle=grad;ctx.fillRect(0,0,W,H);}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener("visibilitychange",function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();',

  // 15. event-wedding — "Fairy Sparkle" (Canvas 2D)
  'event-wedding': '(function(){var isP=self!==top,C=document.getElementById("bg-canvas");if(isP){C.style.background="linear-gradient(180deg,#fdf6f0 0%,#f9ede0 100%)";return;}var ctx=C.getContext("2d"),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener("resize",resize);document.addEventListener("mousemove",function(e){mx=e.clientX;my=e.clientY;});var stars=[];for(var i=0;i<30;i++){stars.push({x:Math.random()*2000,y:Math.random()*1200,s:1+Math.random()*2,phase:Math.random()*Math.PI*2,twinkleSpeed:1+Math.random()*2,vx:(Math.random()-0.5)*0.08,vy:(Math.random()-0.5)*0.08});}var t=0;var raf;function draw(){ctx.clearRect(0,0,W,H);t+=0.016;for(var i=0;i<stars.length;i++){var s=stars[i];s.x+=s.vx;s.y+=s.vy;if(s.x<-5)s.x=W+5;if(s.x>W+5)s.x=-5;if(s.y<-5)s.y=H+5;if(s.y>H+5)s.y=-5;var osc=0.5+0.5*Math.sin(t*s.twinkleSpeed+s.phase);var alpha=0.05+0.15*osc;ctx.beginPath();ctx.arc(s.x%W,s.y%H,s.s,0,Math.PI*2);ctx.fillStyle="rgba(212,165,116,"+alpha+")";ctx.fill();var sparkSize=s.s*2*osc;ctx.beginPath();ctx.moveTo(s.x%W,s.y%H-sparkSize);ctx.lineTo(s.x%W,s.y%H+sparkSize);ctx.strokeStyle="rgba(212,165,116,"+(alpha*0.5)+")";ctx.lineWidth=0.5;ctx.stroke();ctx.beginPath();ctx.moveTo(s.x%W-sparkSize,s.y%H);ctx.lineTo(s.x%W+sparkSize,s.y%H);ctx.stroke();}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener("visibilitychange",function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();',

  // 16. event-music — "Bass Pulse" (Canvas 2D)
  'event-music': '(function(){var isP=self!==top,C=document.getElementById("bg-canvas");if(isP){C.style.background="linear-gradient(135deg,#0a0118 0%,#1a0530 100%)";return;}var ctx=C.getContext("2d"),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener("resize",resize);document.addEventListener("mousemove",function(e){mx=e.clientX;my=e.clientY;});var bpm=128;var beatInterval=60/bpm;var rings=[];for(var i=0;i<6;i++){rings.push({radius:30+i*40,phase:i*0.5,baseRadius:30+i*40,hue:i*60});}var t=0;var beatDrop=0;C.style.pointerEvents="auto";C.addEventListener("click",function(){beatDrop=1;});var raf;function draw(){ctx.clearRect(0,0,W,H);t+=0.016;if(beatDrop>0)beatDrop*=0.95;if(beatDrop<0.01)beatDrop=0;var cx=W/2;var cy=H/2;var beat=Math.abs(Math.sin(t*Math.PI/beatInterval));for(var i=0;i<rings.length;i++){var r=rings[i];var pulse=beat*15+beatDrop*200;var radius=r.baseRadius+pulse*(1-i/rings.length);var hue=(r.hue+t*30)%360;var alpha=0.15*(1-i/rings.length)+beatDrop*0.3;ctx.beginPath();ctx.arc(cx,cy,radius,0,Math.PI*2);ctx.strokeStyle="hsla("+hue+",80%,60%,"+alpha+")";ctx.lineWidth=2+beatDrop*3;ctx.stroke();}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener("visibilitychange",function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();',

  // 17. event-hackathon — "Circuit Glow" (Canvas 2D)
  'event-hackathon': '(function(){var isP=self!==top,C=document.getElementById("bg-canvas");if(isP){C.style.background="linear-gradient(135deg,#0a0a0a 0%,#0a1a0a 100%)";return;}var ctx=C.getContext("2d"),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener("resize",resize);document.addEventListener("mousemove",function(e){mx=e.clientX;my=e.clientY;});var spacing=30;var traces=[];var traceMax=8;function addTrace(){var cols=Math.floor(W/spacing);var rows=Math.floor(H/spacing);var sx=Math.floor(Math.random()*cols);var sy=Math.floor(Math.random()*rows);var dir=Math.random()<0.5?0:1;var len=3+Math.floor(Math.random()*6);var pts=[];for(var i=0;i<len;i++){pts.push({x:sx*spacing,y:sy*spacing});if(dir===0)sx+=1;else sy+=1;if(sx>=cols)sx=0;if(sy>=rows)sy=0;}traces.push({pts:pts,progress:0,speed:0.02+Math.random()*0.02});}for(var i=0;i<traceMax;i++)addTrace();var t=0;var raf;function draw(){ctx.clearRect(0,0,W,H);t+=0.016;var cols=Math.floor(W/spacing);var rows=Math.floor(H/spacing);for(var x=0;x<cols;x++){for(var y=0;y<rows;y++){ctx.beginPath();ctx.arc(x*spacing,y*spacing,1,0,Math.PI*2);ctx.fillStyle="rgba(34,197,94,0.1)";ctx.fill();}}for(var i=traces.length-1;i>=0;i--){var tr=traces[i];tr.progress+=tr.speed;if(tr.progress>1.5){traces.splice(i,1);addTrace();continue;}var activeIdx=Math.floor(tr.progress*tr.pts.length);for(var j=0;j<tr.pts.length-1;j++){var alpha=j<=activeIdx?0.3:0;if(alpha>0){var fade=1-Math.abs(j-activeIdx)/3;if(fade<0)fade=0;ctx.beginPath();ctx.moveTo(tr.pts[j].x,tr.pts[j].y);ctx.lineTo(tr.pts[j+1].x,tr.pts[j+1].y);ctx.strokeStyle="rgba(34,197,94,"+(0.3*fade)+")";ctx.lineWidth=2;ctx.stroke();}}}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener("visibilitychange",function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();',

  // ==================== BLOG (3) ====================

  // 18. blog-tech — "Code Snippet Fall" (Canvas 2D)
  'blog-tech': '(function(){var isP=self!==top,C=document.getElementById("bg-canvas");if(isP){C.style.background="linear-gradient(180deg,#fafafa 0%,#f5f0ff 100%)";return;}var ctx=C.getContext("2d"),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener("resize",resize);document.addEventListener("mousemove",function(e){mx=e.clientX;my=e.clientY;});var words=["const","async","return","import","=> {}",".map()","null","await","export","try {}"];var snippets=[];for(var i=0;i<10;i++){snippets.push({x:Math.random()*2000,y:Math.random()*-1000,word:words[Math.floor(Math.random()*words.length)],speed:0.3+Math.random()*0.3,rot:(Math.random()-0.5)*0.1});}var raf;function draw(){ctx.clearRect(0,0,W,H);ctx.font="11px monospace";for(var i=0;i<snippets.length;i++){var s=snippets[i];s.y+=s.speed;if(s.y>H+30){s.y=-30;s.x=Math.random()*W;s.word=words[Math.floor(Math.random()*words.length)];}ctx.save();ctx.translate(s.x%W,s.y);ctx.rotate(s.rot);ctx.fillStyle="rgba(124,58,237,0.05)";ctx.fillText(s.word,0,0);ctx.restore();}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener("visibilitychange",function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();',

  // 19. blog-personal — "Ink Bleed" (Canvas 2D)
  'blog-personal': '(function(){var isP=self!==top,C=document.getElementById("bg-canvas");if(isP){C.style.background="linear-gradient(180deg,#fafafa 0%,#f5f0ff 100%)";return;}var ctx=C.getContext("2d"),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener("resize",resize);document.addEventListener("mousemove",function(e){mx=e.clientX;my=e.clientY;});var stains=[];for(var i=0;i<5;i++){stains.push({x:Math.random()*1600,y:Math.random()*1000,radius:0,maxRadius:120+Math.random()*80,startTime:Math.random()*10,duration:10});}var t=0;var raf;function draw(){ctx.clearRect(0,0,W,H);t+=0.016;for(var i=0;i<stains.length;i++){var s=stains[i];var elapsed=(t-s.startTime)%s.duration;if(elapsed<0)elapsed+=s.duration;var progress=elapsed/s.duration;s.radius=progress*s.maxRadius;var alpha=0.02*(1-progress*0.5);if(alpha<0)alpha=0;var grad=ctx.createRadialGradient(s.x%W,s.y%H,0,s.x%W,s.y%H,s.radius);grad.addColorStop(0,"rgba(124,58,237,"+alpha+")");grad.addColorStop(0.7,"rgba(124,58,237,"+(alpha*0.5)+")");grad.addColorStop(1,"rgba(124,58,237,0)");ctx.fillStyle=grad;ctx.fillRect(0,0,W,H);if(progress>0.95){s.x=Math.random()*W;s.y=Math.random()*H;s.startTime=t;}}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener("visibilitychange",function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();',

  // 20. blog-newsletter — "Paper Planes" (Canvas 2D)
  'blog-newsletter': '(function(){var isP=self!==top,C=document.getElementById("bg-canvas");if(isP){C.style.background="linear-gradient(180deg,#fafafa 0%,#fff8f0 100%)";return;}var ctx=C.getContext("2d"),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener("resize",resize);document.addEventListener("mousemove",function(e){mx=e.clientX;my=e.clientY;});var planes=[];for(var i=0;i<8;i++){planes.push({x:Math.random()*2000-500,y:100+Math.random()*800,size:10+Math.random()*10,speed:0.5+Math.random()*1,amp:15+Math.random()*20,freq:0.5+Math.random()*0.5,phase:Math.random()*Math.PI*2});}var t=0;var raf;function draw(){ctx.clearRect(0,0,W,H);t+=0.016;for(var i=0;i<planes.length;i++){var p=planes[i];p.x+=p.speed;var yOff=Math.sin(t*p.freq+p.phase)*p.amp;var py=p.y+yOff;if(p.x>W+50){p.x=-50;p.y=100+Math.random()*(H-200);}var angle=Math.atan2(Math.cos(t*p.freq+p.phase)*p.amp*p.freq,p.speed);ctx.save();ctx.translate(p.x,py);ctx.rotate(angle);ctx.beginPath();ctx.moveTo(p.size,0);ctx.lineTo(-p.size/2,-p.size/3);ctx.lineTo(-p.size/4,0);ctx.lineTo(-p.size/2,p.size/3);ctx.closePath();ctx.fillStyle="rgba(245,158,11,0.08)";ctx.fill();ctx.strokeStyle="rgba(245,158,11,0.06)";ctx.lineWidth=0.5;ctx.stroke();ctx.restore();}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener("visibilitychange",function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();',

  // ==================== SECTIONS (12) ====================

  // 21. section-hero-animated — "Particle Explosion" (Canvas 2D)
  'section-hero-animated': '(function(){var isP=self!==top,C=document.getElementById("bg-canvas");if(isP){C.style.background="linear-gradient(135deg,#0a0a0f 0%,#111118 100%)";return;}var ctx=C.getContext("2d"),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener("resize",resize);document.addEventListener("mousemove",function(e){mx=e.clientX;my=e.clientY;});var particles=[];function burst(){particles=[];for(var i=0;i<50;i++){var angle=Math.random()*Math.PI*2;var speed=1+Math.random()*3;particles.push({x:W/2,y:H/2,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,life:1,decay:0.003+Math.random()*0.004});}}burst();var t=0;var lastBurst=0;var raf;function draw(){ctx.clearRect(0,0,W,H);t+=0.016;if(t-lastBurst>4){burst();lastBurst=t;}for(var i=0;i<particles.length;i++){var p=particles[i];p.x+=p.vx;p.y+=p.vy;p.vx*=0.995;p.vy*=0.995;p.life-=p.decay;if(p.life<0)p.life=0;ctx.beginPath();ctx.arc(p.x,p.y,2,0,Math.PI*2);ctx.fillStyle="rgba(200,245,59,"+(0.15*p.life)+")";ctx.fill();}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener("visibilitychange",function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();',

  // 22. section-pricing — "Coin Flip" (Canvas 2D)
  'section-pricing': '(function(){var isP=self!==top,C=document.getElementById("bg-canvas");if(isP){C.style.background="linear-gradient(135deg,#0a0a0f 0%,#111118 100%)";return;}var ctx=C.getContext("2d"),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener("resize",resize);document.addEventListener("mousemove",function(e){mx=e.clientX;my=e.clientY;});var coins=[];for(var i=0;i<6;i++){coins.push({x:150+Math.random()*1400,y:150+Math.random()*700,r:15,phase:Math.random()*Math.PI*2,speed:1+Math.random()*1.5});}var t=0;var raf;function draw(){ctx.clearRect(0,0,W,H);t+=0.016;for(var i=0;i<coins.length;i++){var c=coins[i];var scaleX=Math.cos(t*c.speed+c.phase);var px=c.x%W;var py=c.y%H;ctx.save();ctx.translate(px,py);ctx.scale(scaleX,1);ctx.beginPath();ctx.arc(0,0,c.r,0,Math.PI*2);ctx.fillStyle="rgba(200,245,59,0.1)";ctx.fill();ctx.strokeStyle="rgba(200,245,59,0.06)";ctx.lineWidth=1;ctx.stroke();ctx.restore();}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener("visibilitychange",function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();',

  // 23. section-testimonials — "Star Field" (Canvas 2D)
  'section-testimonials': '(function(){var isP=self!==top,C=document.getElementById("bg-canvas");if(isP){C.style.background="linear-gradient(135deg,#0a0a0f 0%,#0f0f18 100%)";return;}var ctx=C.getContext("2d"),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener("resize",resize);document.addEventListener("mousemove",function(e){mx=e.clientX;my=e.clientY;});var stars=[];for(var i=0;i<100;i++){var depth=Math.random();stars.push({x:Math.random()*2000,y:Math.random()*1200,s:1+depth,speed:0.05+depth*0.15,alpha:depth<0.3?0.2:0.1});}var raf;function draw(){ctx.clearRect(0,0,W,H);for(var i=0;i<stars.length;i++){var s=stars[i];s.x-=s.speed;if(s.x<-5)s.x=W+5;ctx.beginPath();ctx.arc(s.x%W,s.y%H,s.s,0,Math.PI*2);ctx.fillStyle="rgba(200,245,59,"+s.alpha+")";ctx.fill();}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener("visibilitychange",function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();',

  // 24. section-features-bento — "Grid Pulse" (Canvas 2D)
  'section-features-bento': '(function(){var isP=self!==top,C=document.getElementById("bg-canvas");if(isP){C.style.background="linear-gradient(135deg,#0a0a0f 0%,#111118 100%)";return;}var ctx=C.getContext("2d"),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener("resize",resize);document.addEventListener("mousemove",function(e){mx=e.clientX;my=e.clientY;});var spacing=20;var raf;function draw(){ctx.clearRect(0,0,W,H);var cols=Math.ceil(W/spacing);var rows=Math.ceil(H/spacing);for(var x=0;x<cols;x++){for(var y=0;y<rows;y++){var px=x*spacing;var py=y*spacing;var dx=px-mx;var dy=py-my;var dist=Math.sqrt(dx*dx+dy*dy);var maxDist=200;var influence=Math.max(0,1-dist/maxDist);var r=1+influence*3;var alpha=0.04+influence*0.12;ctx.beginPath();ctx.arc(px,py,r,0,Math.PI*2);ctx.fillStyle="rgba(200,245,59,"+alpha+")";ctx.fill();}}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener("visibilitychange",function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();',

  // 25. section-cta — "Gradient Wave" (Canvas 2D)
  'section-cta': '(function(){var isP=self!==top,C=document.getElementById("bg-canvas");if(isP){C.style.background="linear-gradient(135deg,#0a0a0f 0%,#111118 100%)";return;}var ctx=C.getContext("2d"),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener("resize",resize);document.addEventListener("mousemove",function(e){mx=e.clientX;my=e.clientY;});var t=0;var raf;function draw(){ctx.clearRect(0,0,W,H);t+=0.016;var baseY=H*0.7;ctx.beginPath();ctx.moveTo(0,H);for(var x=0;x<=W;x+=2){var y=baseY+Math.sin(x*0.005+t*0.5)*30+Math.sin(x*0.01+t*0.3)*15;if(x===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);}ctx.lineTo(W,H);ctx.lineTo(0,H);ctx.closePath();ctx.fillStyle="rgba(200,245,59,0.05)";ctx.fill();}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener("visibilitychange",function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();',

  // 26. section-faq — "Question Marks" (Canvas 2D)
  'section-faq': '(function(){var isP=self!==top,C=document.getElementById("bg-canvas");if(isP){C.style.background="linear-gradient(135deg,#0a0a0f 0%,#111118 100%)";return;}var ctx=C.getContext("2d"),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener("resize",resize);document.addEventListener("mousemove",function(e){mx=e.clientX;my=e.clientY;});var marks=[];for(var i=0;i<10;i++){marks.push({x:Math.random()*2000,y:Math.random()*1200,size:20+Math.random()*20,speed:0.2+Math.random()*0.3,rot:Math.random()*0.3-0.15,rotSpeed:(Math.random()-0.5)*0.005});}var raf;function draw(){ctx.clearRect(0,0,W,H);for(var i=0;i<marks.length;i++){var m=marks[i];m.y-=m.speed;m.rot+=m.rotSpeed;if(m.y<-50){m.y=H+50;m.x=Math.random()*W;}ctx.save();ctx.translate(m.x%W,m.y);ctx.rotate(m.rot);ctx.font=m.size+"px sans-serif";ctx.fillStyle="rgba(139,92,246,0.06)";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("?",0,0);ctx.restore();}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener("visibilitychange",function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();',

  // 27. section-logo-marquee — "Light Trail" (Canvas 2D)
  'section-logo-marquee': '(function(){var isP=self!==top,C=document.getElementById("bg-canvas");if(isP){C.style.background="linear-gradient(135deg,#0a0a0f 0%,#111118 100%)";return;}var ctx=C.getContext("2d"),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener("resize",resize);document.addEventListener("mousemove",function(e){mx=e.clientX;my=e.clientY;});var dot={x:0,y:H/2,vx:3,trail:[]};var trailLen=100;var raf;function draw(){ctx.clearRect(0,0,W,H);dot.x+=dot.vx;if(dot.x>W||dot.x<0){dot.vx*=-1;}dot.trail.push({x:dot.x,y:H/2});if(dot.trail.length>trailLen)dot.trail.shift();for(var i=0;i<dot.trail.length;i++){var p=dot.trail[i];var alpha=0.3*(i/dot.trail.length);ctx.beginPath();ctx.arc(p.x,p.y,2*(i/dot.trail.length),0,Math.PI*2);ctx.fillStyle="rgba(200,245,59,"+alpha+")";ctx.fill();}ctx.beginPath();ctx.arc(dot.x,H/2,3,0,Math.PI*2);ctx.fillStyle="rgba(200,245,59,0.3)";ctx.fill();}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener("visibilitychange",function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();',

  // 28. section-stats — "Number Rain" (Canvas 2D)
  'section-stats': '(function(){var isP=self!==top,C=document.getElementById("bg-canvas");if(isP){C.style.background="linear-gradient(135deg,#0a0a0f 0%,#111118 100%)";return;}var ctx=C.getContext("2d"),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener("resize",resize);document.addEventListener("mousemove",function(e){mx=e.clientX;my=e.clientY;});var digits=[];var colCount=20;for(var i=0;i<colCount;i++){digits.push({x:(i/colCount)*2000,y:Math.random()*-800,digit:Math.floor(Math.random()*10),speed:0.3+Math.random()*0.3});}var raf;function draw(){ctx.clearRect(0,0,W,H);ctx.font="18px monospace";for(var i=0;i<digits.length;i++){var d=digits[i];d.y+=d.speed;if(d.y>H+20){d.y=-20;d.digit=Math.floor(Math.random()*10);}ctx.fillStyle="rgba(200,245,59,0.05)";ctx.fillText(String(d.digit),d.x%(W+50),d.y);}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener("visibilitychange",function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();',

  // 29. section-navbar — "Top Blur Glow" (Canvas 2D)
  'section-navbar': '(function(){var isP=self!==top,C=document.getElementById("bg-canvas");if(isP){C.style.background="linear-gradient(135deg,#0a0a0f 0%,#111118 100%)";return;}var ctx=C.getContext("2d"),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener("resize",resize);document.addEventListener("mousemove",function(e){mx=e.clientX;my=e.clientY;});var glows=[{x:W*0.2,y:0,size:180,color1:"rgba(200,245,59,0.04)",vx:0.2},{x:W*0.5,y:20,size:140,color1:"rgba(139,92,246,0.03)",vx:-0.15},{x:W*0.7,y:10,size:200,color1:"rgba(200,245,59,0.03)",vx:0.25},{x:W*0.9,y:30,size:120,color1:"rgba(139,92,246,0.04)",vx:-0.1}];var raf;function draw(){ctx.clearRect(0,0,W,H);for(var i=0;i<glows.length;i++){var g=glows[i];g.x+=g.vx;if(g.x<-g.size)g.x=W+g.size;if(g.x>W+g.size)g.x=-g.size;var maxY=H*0.2;if(g.y>maxY)continue;var grad=ctx.createRadialGradient(g.x,g.y,0,g.x,g.y,g.size);grad.addColorStop(0,g.color1);grad.addColorStop(1,"rgba(0,0,0,0)");ctx.fillStyle=grad;ctx.fillRect(0,0,W,maxY);}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener("visibilitychange",function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();',

  // 30. section-footer — "Bottom Wave" (Canvas 2D)
  'section-footer': '(function(){var isP=self!==top,C=document.getElementById("bg-canvas");if(isP){C.style.background="linear-gradient(135deg,#0a0a0f 0%,#111118 100%)";return;}var ctx=C.getContext("2d"),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener("resize",resize);document.addEventListener("mousemove",function(e){mx=e.clientX;my=e.clientY;});var t=0;var raf;function draw(){ctx.clearRect(0,0,W,H);t+=0.016;var baseY=H*0.7;for(var w=0;w<2;w++){var speed=w===0?0.4:0.25;var amp=w===0?25:18;var freq=w===0?0.004:0.006;var off=w*1.5;ctx.beginPath();for(var x=0;x<=W;x+=3){var y=baseY+Math.sin(x*freq+t*speed+off)*amp;if(x===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);}ctx.lineTo(W,H);ctx.lineTo(0,H);ctx.closePath();ctx.fillStyle="rgba(200,245,59,0.04)";ctx.fill();}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener("visibilitychange",function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();',

  // 31. section-how-it-works — "Connecting Dots" (Canvas 2D)
  'section-how-it-works': '(function(){var isP=self!==top,C=document.getElementById("bg-canvas");if(isP){C.style.background="linear-gradient(135deg,#0a0a0f 0%,#111118 100%)";return;}var ctx=C.getContext("2d"),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener("resize",resize);document.addEventListener("mousemove",function(e){mx=e.clientX;my=e.clientY;});var t=0;var raf;function draw(){ctx.clearRect(0,0,W,H);t+=0.016;var cy=H/2;var dotSpacing=W/4;var dots=[{x:dotSpacing,y:cy},{x:dotSpacing*2,y:cy},{x:dotSpacing*3,y:cy}];for(var i=0;i<dots.length-1;i++){ctx.beginPath();ctx.moveTo(dots[i].x,dots[i].y);ctx.lineTo(dots[i+1].x,dots[i+1].y);ctx.strokeStyle="rgba(200,245,59,0.1)";ctx.lineWidth=2;ctx.stroke();}var cycleTime=3;var ct=t%cycleTime;var activeIdx=Math.floor((ct/cycleTime)*3);for(var i=0;i<dots.length;i++){var d=dots[i];var isActive=i===activeIdx;var scale=isActive?1+0.3*Math.sin(t*5):1;var alpha=isActive?0.3:0.15;ctx.beginPath();ctx.arc(d.x,d.y,8*scale,0,Math.PI*2);ctx.fillStyle="rgba(200,245,59,"+alpha+")";ctx.fill();}var totalLen=(dots[2].x-dots[0].x);var progress=(ct/cycleTime);var particleX=dots[0].x+progress*totalLen;ctx.beginPath();ctx.arc(particleX,cy,4,0,Math.PI*2);ctx.fillStyle="rgba(200,245,59,0.4)";ctx.fill();ctx.beginPath();ctx.arc(particleX,cy,8,0,Math.PI*2);ctx.fillStyle="rgba(200,245,59,0.1)";ctx.fill();}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener("visibilitychange",function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();',

  // 32. section-contact — "Radar Waves" (Canvas 2D)
  'section-contact': '(function(){var isP=self!==top,C=document.getElementById("bg-canvas");if(isP){C.style.background="linear-gradient(135deg,#0a0a0f 0%,#111118 100%)";return;}var ctx=C.getContext("2d"),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener("resize",resize);document.addEventListener("mousemove",function(e){mx=e.clientX;my=e.clientY;});var rings=[];for(var i=0;i<5;i++){rings.push({radius:0,phase:i*1.5,maxRadius:Math.max(W,H)*0.6});}var t=0;var raf;function draw(){ctx.clearRect(0,0,W,H);t+=0.016;var cx=W*0.65;var cy=H*0.5;for(var i=0;i<rings.length;i++){var r=rings[i];var elapsed=(t+r.phase)%5;var progress=elapsed/5;var radius=progress*r.maxRadius;var alpha=0.06*(1-progress);if(alpha<0)alpha=0;ctx.beginPath();ctx.arc(cx,cy,radius,0,Math.PI*2);ctx.strokeStyle="rgba(200,245,59,"+alpha+")";ctx.lineWidth=1.5;ctx.stroke();}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener("visibilitychange",function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();'

};
