export default {

  // ============================================================
  // MOBILE APP (6)
  // ============================================================

  // 1. app-ios — "iOS Blur Bubbles" (Canvas 2D)
  'app-ios': `(function(){var isP=self!==top,C=document.getElementById('bg-canvas');if(isP){C.style.background='#0a0a1a';return;}var ctx=C.getContext('2d'),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener('resize',resize);document.addEventListener('mousemove',function(e){mx=e.clientX;my=e.clientY;});var bubbles=[];var colors=['rgba(79,70,229,0.05)','rgba(139,92,246,0.04)','rgba(59,130,246,0.04)'];for(var i=0;i<8;i++){bubbles.push({x:Math.random()*2000,y:Math.random()*2000,r:50+Math.random()*100,vx:(Math.random()-0.5)*0.3,vy:(Math.random()-0.5)*0.3,color:colors[i%colors.length],phase:Math.random()*Math.PI*2});}var t=0;var raf;function draw(){ctx.clearRect(0,0,W,H);t+=0.005;for(var i=0;i<bubbles.length;i++){var b=bubbles[i];b.x+=b.vx+Math.sin(t+b.phase)*0.15;b.y+=b.vy+Math.cos(t+b.phase*1.3)*0.15;if(b.x<-b.r*2)b.x=W+b.r;if(b.x>W+b.r*2)b.x=-b.r;if(b.y<-b.r*2)b.y=H+b.r;if(b.y>H+b.r*2)b.y=-b.r;var grad=ctx.createRadialGradient(b.x,b.y,0,b.x,b.y,b.r);grad.addColorStop(0,b.color);grad.addColorStop(1,'rgba(0,0,0,0)');ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fillStyle=grad;ctx.fill();}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener('visibilitychange',function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();`,

  // 2. app-android — "Material Ripple" (Canvas 2D)
  'app-android': `(function(){var isP=self!==top,C=document.getElementById('bg-canvas');if(isP){C.style.background='#0a0a1a';return;}var ctx=C.getContext('2d'),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener('resize',resize);document.addEventListener('mousemove',function(e){mx=e.clientX;my=e.clientY;});var spacing=25,rippleTime=0,rippleX=W/2,rippleY=H/2,rippleActive=false,lastMx=mx,lastMy=my;var raf;function draw(){ctx.clearRect(0,0,W,H);var moved=Math.abs(mx-lastMx)+Math.abs(my-lastMy);if(moved>3){rippleX=mx;rippleY=my;rippleTime=0;rippleActive=true;lastMx=mx;lastMy=my;}if(rippleActive)rippleTime+=2.5;if(rippleTime>800)rippleActive=false;for(var x=spacing/2;x<W;x+=spacing){for(var y=spacing/2;y<H;y+=spacing){var dx=x-rippleX,dy=y-rippleY,dist=Math.sqrt(dx*dx+dy*dy);var opacity=0.03;if(rippleActive){var waveDist=Math.abs(dist-rippleTime);if(waveDist<60){var amp=1-waveDist/60;opacity=0.03+amp*0.12*Math.max(0,1-rippleTime/800);}}ctx.fillStyle='rgba(52,168,83,'+opacity+')';ctx.fillRect(x-1.5,y-1.5,3,3);}}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener('visibilitychange',function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();`,

  // 3. app-game — "Pixel Blocks" (Canvas 2D)
  'app-game': `(function(){var isP=self!==top,C=document.getElementById('bg-canvas');if(isP){C.style.background='#0a0118';return;}var ctx=C.getContext('2d'),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener('resize',resize);document.addEventListener('mousemove',function(e){mx=e.clientX;my=e.clientY;});var colors=['rgba(245,158,11,0.1)','rgba(239,68,68,0.1)','rgba(139,92,246,0.1)','rgba(34,197,94,0.1)'];var blocks=[];for(var i=0;i<50;i++){blocks.push({x:Math.random()*2000,y:Math.random()*2000,s:3+Math.random()*5,vy:0.3+Math.random()*0.5,rot:Math.random()*Math.PI*2,rotV:(Math.random()-0.5)*0.02,color:colors[Math.floor(Math.random()*colors.length)]});}var raf;function draw(){ctx.clearRect(0,0,W,H);for(var i=0;i<blocks.length;i++){var b=blocks[i];b.y+=b.vy;b.vy+=0.03;b.rot+=b.rotV;if(b.y>H+20){b.y=-20;b.x=Math.random()*W;b.vy=0.3+Math.random()*0.5;}ctx.save();ctx.translate(b.x,b.y);ctx.rotate(b.rot);ctx.fillStyle=b.color;ctx.fillRect(-b.s/2,-b.s/2,b.s,b.s);ctx.restore();}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener('visibilitychange',function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();`,

  // 4. app-fitness — "Heartbeat Line" (Canvas 2D)
  'app-fitness': `(function(){var isP=self!==top,C=document.getElementById('bg-canvas');if(isP){C.style.background='#0a0a0a';return;}var ctx=C.getContext('2d'),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener('resize',resize);document.addEventListener('mousemove',function(e){mx=e.clientX;my=e.clientY;});var offset=0;var raf;function ecg(x){var p=x%200;if(p<80)return 0;if(p<90)return(p-80)*3;if(p<100)return(100-p)*3-15;if(p<110)return-15+(p-100)*4.5;if(p<120)return 30-(p-110)*3;if(p<130)return 0;return 0;}function draw(){ctx.clearRect(0,0,W,H);var cy=H/2;ctx.beginPath();ctx.strokeStyle='rgba(239,68,68,0.3)';ctx.lineWidth=2;ctx.shadowColor='rgba(239,68,68,0.6)';ctx.shadowBlur=8;for(var x=0;x<W+10;x+=2){var val=ecg(x+offset);var y=cy-val;if(x===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);}ctx.stroke();ctx.shadowBlur=0;var peakX=W-((offset%200)<110&&(offset%200)>90?offset%200:0);for(var px=0;px<W;px+=200){var localOff=(px+offset)%200;if(localOff>95&&localOff<115){var glowX=px;var glowY=cy-ecg(px+offset);var grad=ctx.createRadialGradient(glowX,glowY,0,glowX,glowY,30);grad.addColorStop(0,'rgba(239,68,68,0.15)');grad.addColorStop(1,'rgba(239,68,68,0)');ctx.fillStyle=grad;ctx.fillRect(glowX-30,glowY-30,60,60);}}offset+=1.5;}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener('visibilitychange',function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();`,

  // 5. app-finance — "3D Coin" (Three.js)
  'app-finance': `(function(){var isP=self!==top,C=document.getElementById('bg-canvas');if(isP){C.style.background='#0a1628';return;}var W=innerWidth,H=innerHeight,mx=W/2,my=H/2;var scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(75,W/H,0.1,1000),renderer=new THREE.WebGLRenderer({canvas:C,alpha:true});renderer.setSize(W,H);renderer.setPixelRatio(Math.min(devicePixelRatio,2));camera.position.z=5;scene.add(new THREE.AmbientLight(0x404040));var pl=new THREE.PointLight(0xffffff,1,100);pl.position.set(5,5,5);scene.add(pl);var pl2=new THREE.PointLight(0x10b981,0.5,100);pl2.position.set(-3,2,4);scene.add(pl2);document.addEventListener('mousemove',function(e){mx=e.clientX;my=e.clientY;});var coinGeo=new THREE.CylinderGeometry(0.8,0.8,0.1,32);var coinMat=new THREE.MeshPhongMaterial({color:0x10b981,shininess:120,specular:0x44ffaa});var coin=new THREE.Mesh(coinGeo,coinMat);coin.position.x=1.2;coin.rotation.x=Math.PI/2*0.3;scene.add(coin);var t=0;function update(){t+=0.015;coin.rotation.y+=0.02;coin.position.y=Math.sin(t)*0.2;coin.rotation.z=Math.sin(t*0.7)*0.05;var tx=(mx/W-0.5)*0.3;var ty=(my/H-0.5)*0.3;camera.position.x+=(tx-camera.position.x)*0.02;camera.position.y+=(-ty-camera.position.y)*0.02;camera.lookAt(0,0,0);}addEventListener('resize',function(){W=innerWidth;H=innerHeight;renderer.setSize(W,H);camera.aspect=W/H;camera.updateProjectionMatrix();});var raf;function loop(){raf=requestAnimationFrame(loop);update();renderer.render(scene,camera);}loop();document.addEventListener('visibilitychange',function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();`,

  // 6. app-social — "Social Web" (Canvas 2D)
  'app-social': `(function(){var isP=self!==top,C=document.getElementById('bg-canvas');if(isP){C.style.background='#0a0a1a';return;}var ctx=C.getContext('2d'),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener('resize',resize);document.addEventListener('mousemove',function(e){mx=e.clientX;my=e.clientY;});var dots=[];for(var i=0;i<50;i++){dots.push({x:Math.random()*2000,y:Math.random()*2000,vx:(Math.random()-0.5)*0.4,vy:(Math.random()-0.5)*0.4,r:2+Math.random()*2});}var raf;function draw(){ctx.clearRect(0,0,W,H);for(var i=0;i<dots.length;i++){var d=dots[i];var dmx=mx-d.x,dmy=my-d.y,dm=Math.sqrt(dmx*dmx+dmy*dmy);if(dm<200){d.vx+=dmx*0.00008;d.vy+=dmy*0.00008;}d.x+=d.vx;d.y+=d.vy;d.vx*=0.999;d.vy*=0.999;if(d.x<0)d.x=W;if(d.x>W)d.x=0;if(d.y<0)d.y=H;if(d.y>H)d.y=0;ctx.beginPath();ctx.arc(d.x,d.y,d.r,0,Math.PI*2);ctx.fillStyle='rgba(79,70,229,0.4)';ctx.fill();for(var j=i+1;j<dots.length;j++){var dx=d.x-dots[j].x,dy=d.y-dots[j].y,dist=Math.sqrt(dx*dx+dy*dy);if(dist<120){ctx.beginPath();ctx.moveTo(d.x,d.y);ctx.lineTo(dots[j].x,dots[j].y);ctx.strokeStyle='rgba(79,70,229,'+(0.08*(1-dist/120))+')';ctx.stroke();}}}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener('visibilitychange',function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();`,

  // ============================================================
  // CRYPTO (6)
  // ============================================================

  // 7. crypto-nft — "Holographic Shimmer" (Canvas 2D)
  'crypto-nft': `(function(){var isP=self!==top,C=document.getElementById('bg-canvas');if(isP){C.style.background='#0a0118';return;}var ctx=C.getContext('2d'),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener('resize',resize);document.addEventListener('mousemove',function(e){mx=e.clientX;my=e.clientY;});var t=0;var raf;function draw(){ctx.clearRect(0,0,W,H);t+=0.008;var offX=(mx/W)*360;var offY=(my/H)*360;for(var y=0;y<H;y+=4){for(var x=0;x<W;x+=4){var hue=(x*0.3+y*0.3+offX+offY+t*50)%360;var dist=Math.sqrt((x-mx)*(x-mx)+(y-my)*(y-my));var bright=Math.max(0,0.15-dist/3000);if(bright>0.01){ctx.fillStyle='hsla('+Math.floor(hue)+',80%,60%,'+bright+')';ctx.fillRect(x,y,4,4);}}}var grad=ctx.createLinearGradient(mx-300,my-300,mx+300,my+300);grad.addColorStop(0,'hsla('+Math.floor((t*40)%360)+',90%,60%,0.03)');grad.addColorStop(0.5,'hsla('+Math.floor((t*40+120)%360)+',90%,60%,0.06)');grad.addColorStop(1,'hsla('+Math.floor((t*40+240)%360)+',90%,60%,0.03)');ctx.fillStyle=grad;ctx.fillRect(0,0,W,H);}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener('visibilitychange',function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();`,

  // 8. crypto-defi — "DeFi Chain" (Three.js)
  'crypto-defi': `(function(){var isP=self!==top,C=document.getElementById('bg-canvas');if(isP){C.style.background='#0a0118';return;}var W=innerWidth,H=innerHeight,mx=W/2,my=H/2;var scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(75,W/H,0.1,1000),renderer=new THREE.WebGLRenderer({canvas:C,alpha:true});renderer.setSize(W,H);renderer.setPixelRatio(Math.min(devicePixelRatio,2));camera.position.z=5;scene.add(new THREE.AmbientLight(0x404040));var pl=new THREE.PointLight(0xffffff,1,100);pl.position.set(5,5,5);scene.add(pl);var pl2=new THREE.PointLight(0x06d6a0,0.6,100);pl2.position.set(-4,3,3);scene.add(pl2);document.addEventListener('mousemove',function(e){mx=e.clientX;my=e.clientY;});var geo=new THREE.TorusKnotGeometry(1,0.3,128,32);var mat=new THREE.MeshPhongMaterial({color:0x06d6a0,wireframe:true,transparent:true,opacity:0.6});var knot=new THREE.Mesh(geo,mat);scene.add(knot);var t=0;function update(){t+=0.008;knot.rotation.x+=0.004;knot.rotation.y+=0.006;knot.rotation.z+=0.002;var tx=(mx/W-0.5)*1.5;var ty=(my/H-0.5)*1.5;camera.position.x+=(tx-camera.position.x)*0.02;camera.position.y+=(-ty-camera.position.y)*0.02;camera.lookAt(0,0,0);}addEventListener('resize',function(){W=innerWidth;H=innerHeight;renderer.setSize(W,H);camera.aspect=W/H;camera.updateProjectionMatrix();});var raf;function loop(){raf=requestAnimationFrame(loop);update();renderer.render(scene,camera);}loop();document.addEventListener('visibilitychange',function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();`,

  // 9. crypto-exchange — "Trading Candles" (Canvas 2D)
  'crypto-exchange': `(function(){var isP=self!==top,C=document.getElementById('bg-canvas');if(isP){C.style.background='#0a0118';return;}var ctx=C.getContext('2d'),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;generateCandles();}var candles=[];function generateCandles(){candles=[];var count=Math.floor(W/14);for(var i=0;i<count;i++){var open=0.3+Math.random()*0.4;var close=0.3+Math.random()*0.4;var high=Math.max(open,close)+Math.random()*0.1;var low=Math.min(open,close)-Math.random()*0.1;candles.push({open:open,close:close,high:Math.min(high,0.95),low:Math.max(low,0.05),bull:close>open});}}resize();addEventListener('resize',resize);document.addEventListener('mousemove',function(e){mx=e.clientX;my=e.clientY;});var regenTimer=0;var raf;function draw(){ctx.clearRect(0,0,W,H);regenTimer++;if(regenTimer>120){regenTimer=0;var newCandles=[];var count=Math.floor(W/14);for(var i=0;i<count;i++){if(i<count-1&&candles[i+1]){newCandles.push(candles[i+1]);}else{var open=0.3+Math.random()*0.4;var close=0.3+Math.random()*0.4;var high=Math.max(open,close)+Math.random()*0.1;var low=Math.min(open,close)-Math.random()*0.1;newCandles.push({open:open,close:close,high:Math.min(high,0.95),low:Math.max(low,0.05),bull:close>open});}}candles=newCandles;}var cw=10,gap=4;for(var i=0;i<candles.length;i++){var c=candles[i];var x=i*(cw+gap)+gap;var top=Math.min(c.open,c.close)*H;var bot=Math.max(c.open,c.close)*H;var hTop=c.low*H;var hBot=c.high*H;var color=c.bull?'rgba(34,197,94,0.08)':'rgba(239,68,68,0.08)';var wickColor=c.bull?'rgba(34,197,94,0.05)':'rgba(239,68,68,0.05)';ctx.fillStyle=color;ctx.fillRect(x,top,cw,bot-top);ctx.fillStyle=wickColor;ctx.fillRect(x+cw/2-0.5,hTop,1,hBot-hTop);}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener('visibilitychange',function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();`,

  // 10. crypto-token — "Spinning Token" (Three.js)
  'crypto-token': `(function(){var isP=self!==top,C=document.getElementById('bg-canvas');if(isP){C.style.background='#0a0118';return;}var W=innerWidth,H=innerHeight,mx=W/2,my=H/2;var scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(75,W/H,0.1,1000),renderer=new THREE.WebGLRenderer({canvas:C,alpha:true});renderer.setSize(W,H);renderer.setPixelRatio(Math.min(devicePixelRatio,2));camera.position.z=5;scene.add(new THREE.AmbientLight(0x404040));var pl=new THREE.PointLight(0xffffff,1,100);pl.position.set(5,5,5);scene.add(pl);var pl2=new THREE.PointLight(0xf59e0b,0.8,100);pl2.position.set(-3,-2,4);scene.add(pl2);document.addEventListener('mousemove',function(e){mx=e.clientX;my=e.clientY;});var geo=new THREE.OctahedronGeometry(1.2);var mat=new THREE.MeshPhongMaterial({color:0xf59e0b,shininess:100,specular:0xffcc44,flatShading:true});var token=new THREE.Mesh(geo,mat);scene.add(token);var t=0;function update(){t+=0.02;token.rotation.x+=0.015;token.rotation.y+=0.03;token.rotation.z+=0.008;var s=1+Math.sin(t*2)*0.08;token.scale.set(s,s,s);var tx=(mx/W-0.5)*1;var ty=(my/H-0.5)*1;camera.position.x+=(tx-camera.position.x)*0.03;camera.position.y+=(-ty-camera.position.y)*0.03;camera.lookAt(0,0,0);}addEventListener('resize',function(){W=innerWidth;H=innerHeight;renderer.setSize(W,H);camera.aspect=W/H;camera.updateProjectionMatrix();});var raf;function loop(){raf=requestAnimationFrame(loop);update();renderer.render(scene,camera);}loop();document.addEventListener('visibilitychange',function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();`,

  // 11. crypto-dao — "Converging Votes" (Canvas 2D)
  'crypto-dao': `(function(){var isP=self!==top,C=document.getElementById('bg-canvas');if(isP){C.style.background='#0a0118';return;}var ctx=C.getContext('2d'),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener('resize',resize);document.addEventListener('mousemove',function(e){mx=e.clientX;my=e.clientY;});var particles=[];function spawnParticle(){var angle=Math.random()*Math.PI*2;var dist=Math.max(W,H)*0.6+Math.random()*200;return{x:W/2+Math.cos(angle)*dist,y:H/2+Math.sin(angle)*dist,speed:0.3+Math.random()*0.5,size:2+Math.random()*3,angle:angle};}for(var i=0;i<40;i++){var p=spawnParticle();p.x=Math.random()*W;p.y=Math.random()*H;particles.push(p);}var raf;function draw(){ctx.clearRect(0,0,W,H);var cx=W/2,cy=H/2;for(var i=0;i<particles.length;i++){var p=particles[i];var dx=cx-p.x,dy=cy-p.y,dist=Math.sqrt(dx*dx+dy*dy);if(dist<30){var np=spawnParticle();p.x=np.x;p.y=np.y;p.speed=np.speed;p.angle=np.angle;dx=cx-p.x;dy=cy-p.y;dist=Math.sqrt(dx*dx+dy*dy);}var nx=dx/dist,ny=dy/dist;p.x+=nx*p.speed;p.y+=ny*p.speed;var alpha=Math.min(0.4,0.1+dist/(Math.max(W,H)*0.5)*0.3);ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fillStyle='rgba(139,92,246,'+alpha+')';ctx.fill();ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x-nx*dist*0.05,p.y-ny*dist*0.05);ctx.strokeStyle='rgba(139,92,246,'+(alpha*0.3)+')';ctx.stroke();}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener('visibilitychange',function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();`,

  // 12. crypto-minimal — "Constellation" (Canvas 2D)
  'crypto-minimal': `(function(){var isP=self!==top,C=document.getElementById('bg-canvas');if(isP){C.style.background='#0a0118';return;}var ctx=C.getContext('2d'),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener('resize',resize);document.addEventListener('mousemove',function(e){mx=e.clientX;my=e.clientY;});var stars=[];for(var i=0;i<40;i++){stars.push({x:Math.random()*2000,y:Math.random()*2000,vx:(Math.random()-0.5)*0.2,vy:(Math.random()-0.5)*0.2,r:1.5+Math.random()*2,phase:Math.random()*Math.PI*2});}var t=0;var raf;function draw(){ctx.clearRect(0,0,W,H);t+=0.015;for(var i=0;i<stars.length;i++){var s=stars[i];s.x+=s.vx;s.y+=s.vy;if(s.x<0)s.x=W;if(s.x>W)s.x=0;if(s.y<0)s.y=H;if(s.y>H)s.y=0;var twinkle=0.15+Math.sin(t+s.phase)*0.15;ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.fillStyle='rgba(139,92,246,'+twinkle+')';ctx.fill();for(var j=i+1;j<stars.length;j++){var dx=s.x-stars[j].x,dy=s.y-stars[j].y,dist=Math.sqrt(dx*dx+dy*dy);if(dist<100){var lineAlpha=0.08*(1-dist/100);ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.lineTo(stars[j].x,stars[j].y);ctx.strokeStyle='rgba(139,92,246,'+lineAlpha+')';ctx.stroke();}}}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener('visibilitychange',function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();`,

  // ============================================================
  // RESTAURANT (5)
  // ============================================================

  // 13. restaurant-luxury — "Elegant Smoke" (Canvas 2D)
  'restaurant-luxury': `(function(){var isP=self!==top,C=document.getElementById('bg-canvas');if(isP){C.style.background='#1a0f0a';return;}var ctx=C.getContext('2d'),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener('resize',resize);document.addEventListener('mousemove',function(e){mx=e.clientX;my=e.clientY;});var smokes=[];for(var i=0;i<15;i++){smokes.push({x:Math.random()*2000,y:Math.random()*2000,r:60+Math.random()*60,vy:-(0.2+Math.random()*0.2),vx:(Math.random()-0.5)*0.1,phase:Math.random()*Math.PI*2,opacity:0.02+Math.random()*0.02});}var t=0;var raf;function draw(){ctx.clearRect(0,0,W,H);t+=0.003;for(var i=0;i<smokes.length;i++){var s=smokes[i];s.y+=s.vy;s.x+=s.vx+Math.sin(t+s.phase)*0.15;if(s.y<-s.r*2){s.y=H+s.r;s.x=Math.random()*W;}var grad=ctx.createRadialGradient(s.x,s.y,0,s.x,s.y,s.r);grad.addColorStop(0,'rgba(212,165,116,'+s.opacity+')');grad.addColorStop(0.5,'rgba(212,165,116,'+(s.opacity*0.5)+')');grad.addColorStop(1,'rgba(212,165,116,0)');ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.fillStyle=grad;ctx.fill();}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener('visibilitychange',function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();`,

  // 14. restaurant-fast — "Soda Bubbles" (Canvas 2D)
  'restaurant-fast': `(function(){var isP=self!==top,C=document.getElementById('bg-canvas');if(isP){C.style.background='#faf8f5';return;}var ctx=C.getContext('2d'),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener('resize',resize);document.addEventListener('mousemove',function(e){mx=e.clientX;my=e.clientY;});var bubbles=[];for(var i=0;i<25;i++){bubbles.push({x:Math.random()*2000,y:Math.random()*2000,r:5+Math.random()*15,vy:-(0.4+Math.random()*0.8),wobblePhase:Math.random()*Math.PI*2,wobbleAmp:0.3+Math.random()*0.5,wobbleSpeed:0.02+Math.random()*0.02});}var raf;function draw(){ctx.clearRect(0,0,W,H);for(var i=0;i<bubbles.length;i++){var b=bubbles[i];b.y+=b.vy;b.wobblePhase+=b.wobbleSpeed;b.x+=Math.sin(b.wobblePhase)*b.wobbleAmp;if(b.y<-b.r*2){b.y=H+b.r+Math.random()*50;b.x=Math.random()*W;}ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fillStyle='rgba(239,68,68,0.06)';ctx.fill();ctx.beginPath();ctx.arc(b.x-b.r*0.3,b.y-b.r*0.3,b.r*0.2,0,Math.PI*2);ctx.fillStyle='rgba(239,68,68,0.03)';ctx.fill();}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener('visibilitychange',function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();`,

  // 15. restaurant-cafe — "Coffee Steam" (Canvas 2D)
  'restaurant-cafe': `(function(){var isP=self!==top,C=document.getElementById('bg-canvas');if(isP){C.style.background='#faf8f5';return;}var ctx=C.getContext('2d'),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener('resize',resize);document.addEventListener('mousemove',function(e){mx=e.clientX;my=e.clientY;});var wisps=[];for(var i=0;i<10;i++){wisps.push({x:W*0.35+Math.random()*W*0.3,y:H*0.7+Math.random()*H*0.3,r:30+Math.random()*30,vy:-(0.3+Math.random()*0.3),phase:Math.random()*Math.PI*2,drift:0.5+Math.random()*0.5,opacity:0.02+Math.random()*0.02});}var t=0;var raf;function draw(){ctx.clearRect(0,0,W,H);t+=0.008;for(var i=0;i<wisps.length;i++){var w=wisps[i];w.y+=w.vy;w.x+=Math.sin(t*0.8+w.phase)*w.drift*0.3;var life=1-Math.max(0,(H*0.7-w.y)/(H*0.5));if(w.y<H*0.2||life<0){w.y=H*0.7+Math.random()*H*0.3;w.x=W*0.35+Math.random()*W*0.3;life=1;}var currentOp=w.opacity*Math.max(0.1,life);var grad=ctx.createRadialGradient(w.x,w.y,0,w.x,w.y,w.r*(1+(1-life)*0.5));grad.addColorStop(0,'rgba(139,111,71,'+currentOp+')');grad.addColorStop(0.6,'rgba(139,111,71,'+(currentOp*0.4)+')');grad.addColorStop(1,'rgba(139,111,71,0)');ctx.beginPath();ctx.arc(w.x,w.y,w.r*(1+(1-life)*0.5),0,Math.PI*2);ctx.fillStyle=grad;ctx.fill();}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener('visibilitychange',function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();`,

  // 16. restaurant-vegan — "Growing Leaves" (Canvas 2D)
  'restaurant-vegan': `(function(){var isP=self!==top,C=document.getElementById('bg-canvas');if(isP){C.style.background='#f0f9f4';return;}var ctx=C.getContext('2d'),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener('resize',resize);document.addEventListener('mousemove',function(e){mx=e.clientX;my=e.clientY;});var leaves=[];for(var i=0;i<12;i++){leaves.push({x:Math.random()*2000,y:Math.random()*2000,w:8+Math.random()*17,h:4+Math.random()*8,vy:-(0.2+Math.random()*0.3),vx:(Math.random()-0.5)*0.2,rot:Math.random()*Math.PI*2,rotV:(Math.random()-0.5)*0.008,phase:Math.random()*Math.PI*2});}var t=0;var raf;function draw(){ctx.clearRect(0,0,W,H);t+=0.006;for(var i=0;i<leaves.length;i++){var l=leaves[i];l.y+=l.vy;l.x+=l.vx+Math.sin(t+l.phase)*0.2;l.rot+=l.rotV;if(l.y<-40){l.y=H+40;l.x=Math.random()*W;}ctx.save();ctx.translate(l.x,l.y);ctx.rotate(l.rot);ctx.beginPath();ctx.ellipse(0,0,l.w/2,l.h/2,0,0,Math.PI*2);ctx.fillStyle='rgba(22,163,74,0.06)';ctx.fill();ctx.beginPath();ctx.moveTo(-l.w/2,0);ctx.lineTo(l.w/2,0);ctx.strokeStyle='rgba(22,163,74,0.04)';ctx.lineWidth=0.5;ctx.stroke();ctx.restore();}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener('visibilitychange',function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();`,

  // 17. restaurant-bakery — "Flour Dust" (Canvas 2D)
  'restaurant-bakery': `(function(){var isP=self!==top,C=document.getElementById('bg-canvas');if(isP){C.style.background='#fdf6f0';return;}var ctx=C.getContext('2d'),W,H,mx,my;function resize(){W=C.width=innerWidth;H=C.height=innerHeight;mx=W/2;my=H/2;}resize();addEventListener('resize',resize);document.addEventListener('mousemove',function(e){mx=e.clientX;my=e.clientY;});var dust=[];for(var i=0;i<18;i++){dust.push({x:Math.random()*2000,y:Math.random()*2000,r:1+Math.random()*3,vx:(Math.random()-0.5)*0.3,vy:(Math.random()-0.5)*0.3,ax:0,ay:0,phase:Math.random()*Math.PI*2});}var t=0;var raf;function draw(){ctx.clearRect(0,0,W,H);t+=0.01;for(var i=0;i<dust.length;i++){var d=dust[i];d.ax=(Math.random()-0.5)*0.04;d.ay=(Math.random()-0.5)*0.04;d.vx+=d.ax;d.vy+=d.ay;d.vx*=0.98;d.vy*=0.98;d.x+=d.vx;d.y+=d.vy;if(d.x<0)d.x=W;if(d.x>W)d.x=0;if(d.y<0)d.y=H;if(d.y>H)d.y=0;var flicker=0.03+Math.sin(t*2+d.phase)*0.01;ctx.beginPath();ctx.arc(d.x,d.y,d.r,0,Math.PI*2);ctx.fillStyle='rgba(217,119,6,'+flicker+')';ctx.fill();}}function loop(){raf=requestAnimationFrame(loop);draw();}loop();document.addEventListener('visibilitychange',function(){if(document.hidden)cancelAnimationFrame(raf);else loop();});})();`

};
